- name: loops
  hosts: local
  connection: local
  tasks:
  - name: install packages
    ansible.builtin.packages:
      name: "{{item}}"
      state: latest
    loop:
    - nginx
    - mongodb
    - mysql
