- name: Play level variable
  hosts: local
  connection: local
  vars:
    COURSE: Ansible
    DURATION: 10 hours
    TRAINER: karthik reddy
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "course name is: {{ COURSE }},Duration is: {{ DURATION }}, and the trainer is : {{ TRAINER }}"

  - name: print the course info
    COURSE: Ansible play books
    ansible.builtin.debug:
      msg: "course name is: {{ COURSE }},Duration is: {{ DURATION }}, and the trainer is : {{ TRAINER }}"